name: Filtering
on:
  push:
    branches:
      - main
    paths:
    - '.github/workflows'
jobs:
 filter:
  runs-on: ubuntu-latest  
  steps:
    - name: github context
      run: echo "${{toJSON(github.event)}}"