name: WorkFlows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
    - '.github/workflows/*'

jobs:
  first-job:
    runs-on: Windows-Latest
    steps:
    - run: npm node --version
    - run: npm --version
  filter:
    runs-on: ubuntu-latest  
    steps:
      - name: github context
        run: echo "${{toJSON(github.event)}}"
  build:
    runs-on: ubuntu-latest
    steps:
    - run: npm node --version
    - run: npm --version
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Upload static site content
      uses: actions/upload-artifact@v3
      with:
        name: Beta
        path: home\src\tweaks\